apiVersion: networking.k8s.io/v1
kind: Ingress
namespace: go-web-app
metadata:
  name: go-web-app
  annotations:
    
spec:
  ingressClassName: nginx
  rules:
  - host: go-web-app.teepstech.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-web-app
            port:
              number: 80
 
