name: "Continuous Integration go-web-app"

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'
env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_ECR_REPO_NAME: ${{ vars.AWS_ECR_REPO_NAME }}
  REPOSITORY_URI: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.AWS_ECR_REPO_NAME }}
  
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.23
        - name: Build
          run: go build -o go-web-app
        - name: Test
          run: go test ./...

    code-quality:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Run golangci-lint
          uses: golangci/golangci-lint-action@v6
          with:
           version: v1.56.2
    
    docker-image-build:
        defaults:
          run:
            working-directory: go-web-app-EKS-DevOps
        runs-on: ubuntu-latest  
        steps:        
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Build docker image
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./Dockerfile
                push: false
                tags: ${{env.AWS_ECR_REPO_NAME}}
                
    ECR-image-push:
        runs-on: ubuntu-latest
        needs: docker-image-build
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Configure aws credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}
            - name: Login to Amazon ECR
              id: login-ecr
              run: aws ecr get-login-password --region ${{env.AWS_REGION}} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{env.AWS_REGION}}.amazonaws.com
            - name: Push image to Amazon ECR
              run: docker tag ${{env.AWS_ECR_REPO_NAME}} ${{env.REPOSITORY_URI}}:${{github.run_id}}
            - name: Push image to Amazon ECR
              run: docker push ${{env.REPOSITORY_URI}}${{env.AWS_ECR_REPO_NAME}}:${{github.run_id}}
    
    Update_helm_chart:
        runs-on: ubuntu-latest
        needs: ECR-image-push
        env:
          GITHUB_REPO: https://github.com/APtheepan/go-web-app-EKS-DevOps.git
          GITHUB_USER: APtheepan
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        defaults:
          run:
            working-directory: helm/go-web-app-chart
        steps:
          - name: Checkout code
            uses: actions/checkout@v2   
          - name: Update helm chart
            run: |
              BUILD_NUMBER=${{github.run_id}}
              echo $BUILD_NUMBER
              imageTag=$(grep -oP '(?<=helm:)[^ ]+' values.yaml)
              echo $imageTag
              sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml
              git add values.yaml
              git commit -m "Update deployment Image to version \${BUILD_NUMBER}"
              git push https://${{ env.GITHUB_TOKEN }}@github.com/${{ env.GIT_USER_NAME }}/${{ env.GIT_REPO_NAME }} HEAD:main
 
              

          


                
      
           

   
 
    
    

  
        
    


 
  