name: "Continuous Integration go-web-app"

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'
env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_ECR_REPO_NAME: ${{ vars.AWS_ECR_REPO_NAME }}
  REPOSITORY_URI: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_REPO_NAME}
  
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.23
        - name: Build
          run: go build -o go-web-app
        - name: Test
          run: go test ./...

    code-quality:
      runs-on: ubuntu-latest
      steps:
        - name: Run golangci-lint
          uses: golangci/golangci-lint-action@v6
          with:
           version: v1.56.2
    
    docker-image-build:
        runs-on: ubuntu-latest  
        steps:        
            - name: Build docker image
              working-directory: go-web-app-EKS-DevOps
              run: |
                sh 'docker build -t ${AWS_ECR_REPO_NAME} -f Dockerfile .'
    
    ECR-image-push:
        runs-on: ubuntu-latest
        steps:
            - name: Login to Amazon ECR
              id: login-ecr
              run: aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com
            - name: Push image to Amazon ECR
              run: docker tag ${AWS_ECR_REPO_NAME} ${REPOSITORY_URI}${AWS_ECR_REPO_NAME}:${{github.run_id}}
                   docker push ${REPOSITORY_URI}${AWS_ECR_REPO_NAME }:${{github.run_id}}
    
    Update_helm_chart:
        runs-on: ubuntu-latest
        env:
          GITHUB_REPO: https://github.com/APtheepan/go-web-app-EKS-DevOps.git
          GITHUB_USER: APtheepan
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        steps:
          - name: Update helm chart
            working-directory: helm/go-web-app-chart
            run: |
              BUILD_NUMBER=${BUILD_NUMBER}
              echo $BUILD_NUMBER
              imageTag=$(grep -oP '(?<=helm:)[^ ]+' values.yaml)
              echo $imageTag
              sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml
              git add values.yaml
              git commit -m "Update deployment Image to version \${BUILD_NUMBER}"
              git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
 
              

          


                
      
           

   
 
    
    

  
        
    


 
  